### ISSUE TITLE
Bump the openAI library requirements to the latest version

### ISSUE THREAD

**Issue by nvinayvarma189** [Helicone/helicone#1057]
I see that the docs have been updated with instructions for OpenAI v1+ in [this commit](https://github.com/Helicone/helicone/commit/3989087d5237622fee8d13667ca0293447837ecd). However, the latest version of helicone python package still requires the openAI library to be under 0.28.0. This is breaking our build process, it would be great if a new helicone version was released with support for the latest openAI features.

```helicone 1.0.14 requires openai<0.28.0,>=0.27.0, but you have openai 1.3.0 which is incompatible.```

**Comment by tedkornish** [comment]
Also running into the same issue:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
helicone 1.0.14 requires openai<0.28.0,>=0.27.0, but you have openai 1.5.0 which is incompatible.
```

**Comment by Pwuts** [comment]
Helicone integration in `agbenchmark` has also been [disabled](https://github.com/Significant-Gravitas/AutoGPT/commit/056163ee57d8f6374c724df71060cd508ffdaed6) because of this.

**Comment by nileshtrivedi** [comment]
Any update on this? Got a conflict while trying to use [gpt-researcher](https://github.com/assafelovic/gpt-researcher/)

**Comment by nileshtrivedi** [comment]
@maamalama This has not been "completed" because helicone-python is [still using openai 0.27.0](https://github.com/Helicone/helicone/blob/main/helicone-python/pyproject.toml#L12)
