### ISSUE TITLE
Images  as bytes store in S3 and serve back to the UI

### ISSUE THREAD

**Issue by chitalian** [Helicone/helicone#1062]

**Comment by bkowshik** [comment]
New user to Helicone here and the experience so far has been positive. 👍 

Ref: https://platform.openai.com/docs/guides/vision

I have a couple of use-cases with GPT 4 Vision APIs. I am assuming this is the issue to track work on displaying images that were part of the requests, where images could be stored locally or say in the cloud like you mentioned with S3. Is that right?

Any ETA / priority on this?

**Comment by glesperance** [comment]
Does this work with anthropic? Ive been having trouble getting it to work with non openai models.
