### ISSUE TITLE
Azure OpenAI lanchain example not working

### ISSUE THREAD

**Issue by mouhannadali** [Helicone/helicone#1114]
I am trying to integrate Helicone with Azure-OpenAI using lanchain as in the following link:
https://docs.helicone.ai/getting-started/integration-method/azure

but when I am trying to send a message, I am getting the following error:
"Completions.create() got an unexpected keyword argument 'headers'",

I am using
langchain
Version: 0.0.343

openai==1.3.6

**Comment by mouhannadali** [comment]
it is wokring whith default_header in case I set: openai_api_base="https://oai.hconeai.com/openai",
but if I follow the waring: `UserWarning: As of openai>=1.0.0, if `deployment_name` (or alias `azure_deployment`) is specified then `openai_api_base` (or alias `base_url`) should not be. Instead use `deployment_name` (or alias `azure_deployment`) and `azure_endpoint`.`
and use `azure_endpoint="https://oai.hconeai.com/openai",`
then it will not work

**Comment by AI091** [comment]
the docs are not updated to reflect this and I had to do the same as @mouhannadali, please update the docs for azureOpenAI langchain integration
