### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by dakshgup** [Helicone/helicone#1202]
Path: /getting-started/integration-method/azure

Azure says use openai.AzureOpenAI, not openai.OpenAI. 

More info:

https://learn.microsoft.com/en-us/azure/ai-services/openai/quickstart?tabs=command-line%2Cpython-new&pivots=programming-language-python

**Comment by colegottdank** [comment]
Hey @dakshthemaker, I'm a bit confused about where this error is. Are you able to clarify? Thank you!

**Comment by dakshgup** [comment]
@colegottdank the docs seem outdated, they say use 
`openai.OpenAI`

But the MSFT docs (which are correct) say:
`openai.AzureOpenAI`
