### ISSUE TITLE
Exposure of SUPABASE_SERVICE_ROLE_KEY on GitHub

### ISSUE THREAD

**Issue by arpagon** [Helicone/helicone#132]
Description: A team member accidentally published the SUPABASE_SERVICE_ROLE_KEY on GitHub, which is a secret key used by the Supabase service to authenticate requests and perform operations on behalf of a service role. This key is used to grant permissions to specific resources within the Supabase project. As a result, the key is now accessible to anyone who has access to the repository, which can lead to potential security breaches and unauthorized access to team resources.

Actions Taken:

- The team member immediately removed the key from the repository to prevent unauthorized access.
- The team member revoked the exposed key from the Supabase service to prevent anyone from using it to access team resources.
- The team member generated a new key and updated the service to use the new key.
- The team reviewed the code to ensure that no other sensitive information is being exposed.
- The team member notified the team about the issue and the actions taken to fix it.

It is important for the team to be aware of the potential risks associated with accidentally publishing sensitive information on public repositories. It is recommended to implement security measures such as:

- Use environment variables to store sensitive information instead of hardcoding them in the code.
- Implement code reviews and automated tools to detect and prevent the publishing of sensitive information.
- Provide training and education to team members on the importance of keeping sensitive information secure.

By taking these steps, the team can help prevent potential security breaches and protect sensitive information from unauthorized access.

**Comment by chitalian** [comment]
Hi @arpagon, sorry to hear that. We use `.env` files for local development.

Would you like to make a PR to our README to instruct users and suggest the best way to go about this?

**Comment by arpagon** [comment]
Let's clarify something because I might be wrong. 

https://github.com/Helicone/helicone/blob/c9b72c8df9c42335bc5756afa3d48ec5c17cc2af/worker/wrangler.toml#L6

Isn't the production SUPABASE_SERVICE_ROLE_KEY?

**Comment by arpagon** [comment]
Now I understand that this is not the production key. ok, I will collaborate a little in the documentation. Thank you very much.

![image](https://user-images.githubusercontent.com/824129/224440591-f22c24ef-1b98-4fb9-a39f-7f8c7768cf97.png)

**Comment by chitalian** [comment]
@arpagon luckily this specific key is only for localhost, so leaking that speicifc key is OK

**Comment by chitalian** [comment]
Hopefully this will prevent this from happening again
https://github.com/Helicone/helicone/pull/136
