### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by Pau-Lozano** [Helicone/helicone#1329]
Path: /getting-started/integration-method/custom

It seems the Custom Model NodeJS @helicone/helicone client library doesn't export anything called HeliconeAsyncConfiguration as shown in the documentation [https://docs.helicone.ai/getting-started/integration-method/custom](url)

Thanks!

**Comment by chitalian** [comment]
This is correct, we just give this as a reference so you can copy and paste it. 

This should take care of your issue:
https://github.com/Helicone/helicone/issues/1351

Sorry the the inconvience
