### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by mobob** [Helicone/helicone#1402]
Path: /features/advanced-usage/custom-properties

Looking at the top Node sample, the use of an f string has me thinking this isn't quite right ;) Also the use of the OpenAIApi type i don't think is accurate (perhaps on an older build than i'm on).

I think something like this might be closer to what it should be, but i haven't got this working yet 🙃:

```typescript
import {OpenAI} from "openai";
const configuration = {
  apiKey: process.env.OPENAI_API_KEY,
  basePath: "https://oai.hconeai.com/v1",
  defaultHeaders: {
    "Helicone-Auth": `Bearer ${HELICONE_API_KEY}`,
    "Helicone-Property-Session": "24",
    "Helicone-Property-Conversation": "support_issue_2",
    "Helicone-Property-App": "mobile",
  },
};
const openai = new OpenAI(configuration);
```

**Comment by colegottdank** [comment]
Fixed here: https://github.com/Helicone/helicone/pull/1629

Thank you!!!
