### ISSUE TITLE
It is not clear the time windows when looking at the graphs

### ISSUE THREAD

**Issue by chitalian** [Helicone/helicone#149]
This is requests per week, we should maybe state per week somewhere

<img width="820" alt="Screenshot 2023-03-17 at 3 51 45 PM" src="https://user-images.githubusercontent.com/26822232/226015687-aa45159b-a967-44ba-9831-fa6050826572.png">

**Comment by aavetis** [comment]
agree, also, you have significant space on the dashboard page to make them larger / more interactive / etc.

**Comment by chitalian** [comment]
This is stale. We are doing a major Dashboard Revamp and will include this here

https://github.com/Helicone/helicone/issues/965
