### ISSUE TITLE
Clear user feedback via API

### ISSUE THREAD

**Issue by mllocs** [Helicone/helicone#1578]
I'm using the API to send user feedback following these docs: https://docs.helicone.ai/features/advanced-usage/feedback

There's any way to remove the feedback? I can override it but I don't see how to clear it. Sending a null value returns an error: "Invalid rating format. Expected a boolean.".

Thanks.

**Comment by colegottdank** [comment]
Hi, we do not have a way to remove feedback atm. We have plans to add this support soon. I will update here when that is completed.
