### ISSUE TITLE
Add docker image?

### ISSUE THREAD

**Issue by alexkreidler** [Helicone/helicone#158]
This looks like a cool project! I'd love to try it out quickly, and the easiest way to do that (instead of setting up NPM, Supabase, and the  Cloudflare workers) would be to run a docker image. I'd also suggest putting screenshots or a demo gif on the Github README so people can get a sense of the UI without going to the website. Thanks for your work on this and open-sourcing it!

**Comment by aavetis** [comment]
I have a WIP of this. Running web and supabase is pretty easy, but I’m not sure how to handle the worker as it seems to need a setup with cloudflare workers etc. etc.
@chitalian any pointers that might give us a head start?

**Comment by Tor101** [comment]
#233 I think solves it. no?

**Comment by chitalian** [comment]
> #233 I think my pr solves it. no?

Oh awesome! I totally missed this, sorry! I left a comment

**Comment by alexkreidler** [comment]
Thanks to everyone working on this #233, #244, we now have a `docker` folder in the repo with instructions. A few more suggestions:
1. Get rid of the `Makefile` and just use the builtin [docker-compose `build:` YAML field:](https://docs.docker.com/compose/compose-file/build/#build-definition)
2. Combine the Helicone `docker-compose.yml` with the [supabase one](https://github.com/supabase/supabase/blob/master/docker/docker-compose.yml), so that people don't even have to install the supabase CLI on their machine. Potentially we could get rid of some unneeded services like `realtime`, `imgproxy`, or `storage` (Need some input from core devs on what Helicone uses/depends on)
3. Add a section to the README with the docker setup instructions

Making both those changes would mean you can just run `git clone https://github.com/Helicone/helicone; cd docker; docker-compose up` and start playing with Helicone!

**Comment by chitalian** [comment]
@alexkreidler Thanks for your suggestions. I think I covered it all here
https://github.com/Helicone/helicone/pull/374
