### ISSUE TITLE
Prompt formatting tracking

### ISSUE THREAD

**Issue by chitalian** [Helicone/helicone#209]
Let's kick off the discussion about how we can best support the ability to track prompt formats and how prompts were constructed. 

Our main focus is ensuring the UX is good and there are no major code changes/workflow disruptions to add this logging.

We currently have formatted templates https://docs.helicone.ai/advanced-usage/templated-prompts. But as [@ianbicking from HN](https://news.ycombinator.com/reply?id=35280758&goto=item%3Fid%3D35279155%2335280758) mentioned, they might want to add formatting details and not have helicone format the prompt for them.

Here is one idea we can do

```python
template = {
    "prompt": "Write an amazing poem about Helicone",
    "promptFormat": "Write an amazing poem about Helicone"
}

serialized_template = json.dumps(template)

openai.Completion.create(
    model="text-davinci-003",
    prompt=serialized_template,
    headers={
        'Helicone-Prompt-Format': 'on',
    }
)

```

**Comment by aavetis** [comment]
lots of prompt templating options floating around, hard to say which one would be the best to use imo; and whether you'll want to fully invest in sophisticated templating
