### ISSUE TITLE
User rate limiting

### ISSUE THREAD

**Issue by chitalian** [Helicone/helicone#211]
Taken from https://github.com/Helicone/helicone/discussions/140

We should have the ability to easily rate limit a user for X # of requests per day or something like that. 

Rate limiting by user. See this [super simple implementation](https://github.com/Nutlope/roomGPT/blob/main/pages/api/generate.ts#L41-L46) of a user ID rate limiter implemented with Upstash

Something like this
```typescript
{
  `helicone-enable-user-rate-limit': 'true'
  `helicone-user-requests`: "# of requests per cadence"
  `helicone-user-cadence`: "# of seconds" 
}
```

From @aavetis
> Well those 2 params are pretty much [the only thing](https://github.com/Nutlope/roomGPT/blob/main/pages/api/generate.ts#L22-L29) people seem to use at the moment with redis caches :)

**Comment by BarakOshri** [comment]
This is now merged. For user rate limiting of 1000 requests in 60 seconds, add the header:

```
"Helicone-RateLimit-Policy": "1000;w=60;s=user",
```

Docs: https://docs.helicone.ai/advanced-usage/custom-rate-limits
