### ISSUE TITLE
Be able to block users 

### ISSUE THREAD

**Issue by chitalian** [Helicone/helicone#212]
Taken from https://github.com/Helicone/helicone/discussions/140

We should be able to block bad actors or users. We need some user management section with in the UI to say "restrict traffic for this user"

**Comment by aavetis** [comment]
very much related to #219 and #218, logic being that you'd identify those issues and ultimately ban (temporarily or permanently, etc.) the users making those requests

**Comment by chitalian** [comment]
Closing now - We can reopen if this becomes more widely requested
