### ISSUE TITLE
Vercel AI SDK Config Example

### ISSUE THREAD

**Issue by Yonom** [Helicone/helicone#2152]
Hey, I saw that there's an example missing for the Vercel AI SDK. Here's what I had to do to set helicone up

```patch
-import { openai } from "@ai-sdk/openai";
+import { createOpenAI } from "@ai-sdk/openai";

+const openai = createOpenAI({
+  baseURL: "https://oai.hconeai.com/v1",
+  headers: {
+    "Helicone-Auth": "Bearer pk-helicone-xx",
+  },
+});
```

Let me know if this is interesting to add to the repo

**Comment by MaryOfLA** [comment]
What about using [groq](https://sdk.vercel.ai/providers/ai-sdk-providers/groq#provider-instance)? The groq `baseURL` is needed.

**Comment by caelinsutch** [comment]
Is there a way to add headers to the ai sdk?

**Comment by Yonom** [comment]
@caelinsutch you can use the `createOpenAI` etc methods and pass in headers there (see my code example above)

**Comment by colegottdank** [comment]
Thanks @Yonom!!!! Added your example to our docs!

https://github.com/Helicone/helicone/pull/2319

**Comment by Yonom** [comment]
WOOHOO thanks @colegottdank !!
