### ISSUE TITLE
Feedback on requests

### ISSUE THREAD

**Issue by chitalian** [Helicone/helicone#217]
We should have the ability to give feedback for specific requests.

For a given request we should be able to provide feedback and be able to report human feedback and compare across prompts and models

**Comment by aavetis** [comment]
interesting to think about how to make sure that feedback doesn't get buried in requests history. assuming not every request would have feedback associated, maybe this could be tracked somewhere else on the app, but still be tracked back to a request

**Comment by subhajit20** [comment]
Hely @aavetis  @chitalian  is there any open issues for me which I could try to solve ?

**Comment by chitalian** [comment]
> Hely @aavetis @chitalian is there any open issues for me which I could try to solve ?

Hi @subhajit20 we really need better documentation around self hosting and self deployment. I think this is a really good starter task for someone new to the project. It is related to this ticket
https://github.com/Helicone/helicone/issues/158

I added a channel called contributing on our discord where you can ask some questions: https://discord.gg/JHTGfBmD

Also, feel free to DM me on Discord and I can help you onboard onto the repo.

**Comment by chitalian** [comment]
MVP of feedback is completed
