### ISSUE TITLE
High-level stats (e.g. Tokens used by user id)

### ISSUE THREAD

**Issue by jonnyk20** [Helicone/helicone#223]
It would be great to get an overview of token usage by users without exporting the data and doing the calculations elsewhere. This is the main thing I'm using Helicone to keep track of.

**Comment by chitalian** [comment]
We would like to see the same high level stats in the dashboard but per user

**Comment by chitalian** [comment]
We added users page here. This should capture what you are looking for. 
<img width="1338" alt="Screenshot 2023-09-13 at 12 37 00 PM" src="https://github.com/Helicone/helicone/assets/26822232/a129121a-52a7-4ce7-97ad-825a64d3a7c0">
