### ISSUE TITLE
Issue on docs: Anthropic JavaScript SDK Integration

### ISSUE THREAD

**Issue by Evgastap** [Helicone/helicone#2245]
Path: /integrations/anthropic/javascript

Using the `@vercel/ai` library, I had to set the baseUrl to `https://anthropic.helicone.ai/v1` instead of `https://anthropic.helicone.ai` as pointed out in the docs in order to get things working. Not sure if that applies to the regular anthropic provider, but just an FYI!

**Comment by chitalian** [comment]
Thank you!
https://github.com/Helicone/helicone/commit/85c2482c374cd02bb623e9fd8b5793f29bf0dd19
