### ISSUE TITLE
Dependency Bloat (NodeJS)

### ISSUE THREAD

**Issue by tim-elam** [Helicone/helicone#2256]
Unfortunately, we're dropping Helicone at DemoFox because of dependency bloat when migrating from version 2 -> 3. We run on Lambda and have a hard platform limit of 250Mb unzipped function size. Before upgrading (using 2.1.11), our serverless deployment zip file was **81.6Mb**. After upgrading to 3.0.2, our deployment zip file is **270.7 MB**.

Please update here if/when this is resolved (ideally by changing optional 3rd-party integrations from `dependencies` to `devDependencies`) and we will add an item to the backlog to reinstall Helicone into our pipeline.

**Comment by chitalian** [comment]
This was fix in the latest version`3.1.0`
https://github.com/Helicone/helicone/pull/2248

**Comment by tim-elam** [comment]
Oh, I just realized the suggestion I fixed of moving them to devDependencies is probably not correct. If the package makes runtime calls to LLM providers depending on the customer's specific use case, they should be peerDependencies instead 😅. But if those packages are just used during development of the Helicon itself, devDependencies is correct and you can disregard this message.
