### ISSUE TITLE
[Bug]: Azure integration does not work

### ISSUE THREAD

**Issue by ahmedriad1** [Helicone/helicone#2348]
### What happened?

I followed [this](https://docs.helicone.ai/integrations/azure/javascript) guide to setup azure openai with helicone and it keeps erroring out:
```
{ code: '404', message: 'Resource not found' }
```

it even shows up in my dashboard:
![CleanShot 2024-07-27 at 22 48 26@2x](https://github.com/user-attachments/assets/9e85aa26-0fc2-42bb-9d4f-f4f216b0c56f)

my setup:
```ts
export const openai = new OpenAI({
  baseURL: `https://oai.helicone.ai/openai/deployments/${env.AZURE_OPENAI_DEPLOYMENT_NAME}`,
  defaultHeaders: {
    "Helicone-Auth": `Bearer ${env.HELICONE_API_KEY}`,
    "Helicone-OpenAI-API-Base": `https://${env.AZURE_OPENAI_RESOURCE_NAME}.openai.azure.com/`,
    "api-key": env.AZURE_OPENAI_KEY,
  },
  defaultQuery: { "api-version": "2024-05-13" },
});

const response = await openai.chat.completions.create({
  // ...
});  // ❌ does not work
```

However, when using azure's sdk, it works just fine, even with the same environment variables:
```ts
const azureOpenai = new AzureOpenAI.OpenAIClient(
  `https://${env.AZURE_OPENAI_RESOURCE_NAME}.openai.azure.com/`,
  new AzureOpenAI.AzureKeyCredential(env.AZURE_OPENAI_KEY),
);

const response = await azureOpenai.getChatCompletions(
  env.AZURE_OPENAI_DEPLOYMENT_NAME,
  // ...
); // ✅ works just fine!
```

I even tried the `HeliconeAsyncLogger` and it doesn't work too!

**Comment by chitalian** [comment]
Thank you @ahmedriad1 for raising this issue. Glad you were able to find a solution that works for you. 

We will update the docs to reflect your findings, are there any other issues here?

**Comment by adaryabegi** [comment]
Any news on this? I cannot use Azure with Helicone??

**Comment by colegottdank** [comment]
Hi @ahmedriad1 and @adaryabegi, I just tested and it worked for me just fine:

`import OpenAI from "openai";

const openai = new OpenAI({
  baseURL: "https://oai.hconeai.com/openai/deployments/{DEPLOYMENT_NAME}",
  defaultHeaders: {
    "Helicone-Auth": `Bearer ${process.env.HELICONE_API_KEY}`,
    "Helicone-OpenAI-API-Base": process.env.AZURE_OPENAI_BASE_URL,
    "api-key": process.env.AZURE_OPENAI_API_KEY,
  },
  defaultQuery: { "api-version": "{API_VERSION}" },
});

const data = await openai.chat.completions.create({
    model: "gpt-4",
    messages: [{ role: "user", content: "Say Hi" }],
    stream: false,
  });

console.log(data);
`

<img width="1183" alt="Screenshot 2024-09-26 at 3 11 01 PM" src="https://github.com/user-attachments/assets/342f8c17-ee2d-4afa-811e-5aa282840b09">

Are you still experiencing issues?

**Comment by ahmedriad1** [comment]
Hi @chitalian and @colegottdank,

I was finally able to figure it out! I was using [llamaindex's TS SDK](https://ts.llamaindex.ai/) and this was how I solved it:

```ts
import { OpenAI } from 'llamaindex';

return new OpenAI({
  additionalSessionOptions: {
    baseURL: `https://oai.helicone.ai/openai/deployments/${process.env.AZURE_DEPLOYMENT_NAME}`,
    defaultHeaders: {
      'Helicone-Auth': `Bearer ${process.env.HELICONE_API_KEY}`,
      'Helicone-OpenAI-Api-Base': `https://${process.env.AZURE_RESOURCE_NAME}.openai.azure.com`,
      'api-key': process.env.AZURE_SECRET_KEY,
    },
    defaultQuery: {
      'api-version': '2024-08-01-preview',
    },
  },
});
```

Would be great if you can update your docs to include it since llamaindex is not intuitive at all and passing config under the `azure` param doesn't work. Thanks!
