### ISSUE TITLE
API not functional - authentication issues even with read key

### ISSUE THREAD

**Issue by RowanAldean** [Helicone/helicone#2760]
Path: /use-cases/getting-user-requests

None of the API is functional, including the `https://api.helicone.ai/v1/request/query`

### Setup
- We use Azure OpenAI and Helicone via setting the base in the headers.
- Created a new read/write key from the UI
- Using the new read/write key via `curl` or `postman` always fails.
- Using the new key in the URL as so `https://api.helicone.ai/sk-<my-key>/v1/request/query` also fails.

### Error Shown (for all attempts)
```
{
    "error": "No API key found",
    "trace": "isAuthenticated.error"
}
```

**Comment by kavinvalli** [comment]
Hi @RowanAldean, can you please confirm if this is how you're sending the API Key?
<img width="821" alt="Screenshot 2024-10-10 at 3 52 43 pm" src="https://github.com/user-attachments/assets/f00dd18b-0b5d-4cc0-b983-55e3daa2286e">

**Comment by RowanAldean** [comment]
Confirmed @kavinvalli 

![CleanShot 2024-10-10 at 23 55 20@2x](https://github.com/user-attachments/assets/13450ac0-8baa-436c-b3b3-dd608b7b3538)

Going through your network requests now and seeing it uses `eu.api.helicone` so ignore that i'm playing around with that.

fyi: I am getting responses now (although lots of errors).

**Comment by kavinvalli** [comment]
@RowanAldean Yes, since you're in an EU data region, `eu.api.helicone` should work as intended. You're saying that this api gives back the responses but has errors, right?
Would you be able to send a screenshot sample of a response that you're getting back. That would be very helpful in debugging the issue faster, thank you!

**Comment by RowanAldean** [comment]
You can see the error here:

[error-helicone-eu-api.txt](https://github.com/user-attachments/files/17335214/error-helicone-eu-api.txt)

Here's a screenshot. The only kind of functional endpoint is `https://eu.api.helicone.ai/v1/property/query` otherwise the rest give this same error:

### error output:
```
ValidateError
    at ExpressTemplateService.getValidatedArgs (/usr/src/app/valhalla/jawn/node_modules/@tsoa/runtime/dist/routeGeneration/templates/express/expressTemplateService.js:70:19)
    at RequestController_getRequests (/usr/src/app/valhalla/jawn/dist/valhalla/jawn/src/tsoa-build/public/routes.js:3435:45)
    at Layer.handle [as handle_request] (/usr/src/app/valhalla/jawn/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/valhalla/jawn/node_modules/express/lib/router/route.js:149:13)
    at runAuthenticationMiddleware (/usr/src/app/valhalla/jawn/dist/valhalla/jawn/src/tsoa-build/public/routes.js:5246:17)
```

### error screenshot:
![CleanShot 2024-10-11 at 00 11 13@2x](https://github.com/user-attachments/assets/3a9c9e49-6381-464a-9c82-d247c51ef058)

**Comment by RowanAldean** [comment]
Ok, seems we have solved this by understanding that the endpoint **requires a body**.

Taking the JSON body from [the docs](https://docs.helicone.ai/rest/request/post-v1requestquery) and putting into Postman/curl worked.

### Solution Recap
- EU users need to use `eu.api.helicone.ai` as their target URL
- Endpoints that support a JSON body have no useful error message, **you need to have a well formed body** as outlined in docs.
- The [export scripts](https://github.com/Helicone/helicone/blob/main/examples/export/typescript/index.ts) can be used in Python/Typescript to programmatically do this, **where the target needs `eu` appended too.**
