### ISSUE TITLE
Prompt Injection detection and alerting

### ISSUE THREAD

**Issue by chitalian** [Helicone/helicone#288]
We can do a similarity score between the response and the initial prompt to detect % likelyhood that there was a prompt injection and flag over some default threshold (80%?)

**Comment by woop** [comment]
Hey folks,

Would it make sense for us to integrate https://github.com/woop/rebuff here? We're investing very heavily into making it a best in class prompt injection and observability framework. I think it fits in nicely with Helicone.

**Comment by chitalian** [comment]
Hi @woop thanks for sharing! This would be awesome!
