### ISSUE TITLE
Expand API filter to get aggregated cost metrics

### ISSUE THREAD

**Issue by chitalian** [Helicone/helicone#295]
We want the ability to get aggregated cost metric with filters.

ex: 
"is there any way to add openAI keys using helicone API and get the usage costs for each key ?" - Ivo

https://discord.com/channels/1020597994703310878/1021699161831251968/1095740857090592768

**Comment by aavetis** [comment]
consider extending this to support different "grouping mechanisms" at the api level, maybe in that graphql you have. and when we're talking about grouping costs, you're really just grouping requests, right?

e.g. group costs by user; group costs by api key; group cost by ...

**Comment by chitalian** [comment]
Added, a basic version of this! @aavetis I like your idea of a group by key
