### ISSUE TITLE
Add retention TTL to sensitive request fields

### ISSUE THREAD

**Issue by DragonStuff** [Helicone/helicone#307]
[From OpenAI's API data usage policy](https://openai.com/policies/api-data-usage-policies):
> Any data sent through the API will be retained for abuse and misuse monitoring purposes for a maximum of 30 days, after which it will be deleted (unless otherwise required by law).

Helicone retains all request data at the moment, and this is totally understandable if you wish to debug issues or tune your model. However, if you are developing an application where end-users could potentially send sensitive data to the Helicone API, it would be best to be able to tell users "your request data will be deleted automatically in x time" or immediately, with no TTL.

This setting would be fine to set account-wide, or on messages with a certain header such as `sensitive: true`.

Helicone has a distinct advantage in being able to track costs per user, model, key etc, but tracking the actual messages themselves may not be necessary. This could also be implemented as a "metadata only mode" where only the following fields are kept:
* time
* total tokens
* user
* model

**Comment by chitalian** [comment]
This is such a feature request @DragonStuff thanks

**Comment by chitalian** [comment]
Added to our roadmap
