### ISSUE TITLE
Usage gauge incorrect

### ISSUE THREAD

**Issue by spark-ming** [Helicone/helicone#310]
Thanks for the awesome work in this service! Have found it immensely helpful as we start testing our application with users.

I noticed that #309 introduced increased limits, but the gauge is still counting against the old limit. I'm sure this is going to be fixed but just wanted you to be aware 😁

<img width="1497" alt="image" src="https://user-images.githubusercontent.com/47765538/233760509-5c6f978f-754c-445d-81d9-f82161bc9046.png">

**Comment by chitalian** [comment]
Hi @spark-ming - try to refresh the usage page, it might take a few minutes for the change to get added, please let me know if you are still seeing this

**Comment by spark-ming** [comment]
Just did a hard refresh and looks like it's fixed now! Thanks

<img width="706" alt="image" src="https://user-images.githubusercontent.com/47765538/233884600-75b0c7e9-7d2d-4327-9066-09c4618b02db.png">
