### ISSUE TITLE
Does not cache when user properties are changed

### ISSUE THREAD

**Issue by spark-ming** [Helicone/helicone#311]
Love the caching feature! Makes the request so much quicker when it's seen before, and more predictable too.

However, I noticed an issue when using it together with user properties. Say I have the following headers:

```ts
const headers =  {
  "Helicone-Cache-Enabled": "true",
  "Helicone-Property-App": "my-application",
  "Helicone-Property-Session-": "12345689",
},
```

`Helicone-Property-App` is static so that's fine, but when the session ID `Helicone-Property-Session` changes, it no longer uses the cache. 

Would love to be able to have the cache ignore certain headers.

**Comment by chitalian** [comment]
oh yes! Caching does not support this, but it should not be too hard to enable this. I will get on this probably sometime this week

**Comment by spark-ming** [comment]
> oh yes! Caching does not support this, but it should not be too hard to enable this. I will get on this probably sometime this week

Sounds good. Are you thinking just making all user properties ignored in caching? Or for the user to select which ones should be ignored.

**Comment by chitalian** [comment]
> for the user to select which ones should be ignored.

This one.

What would you perfer?

**Comment by spark-ming** [comment]
> > for the user to select which ones should be ignored.
> 
> This one.
> 
> What would you perfer?

I think this is the most flexible, as some people may use user properties to refresh the cache. Not sure of the use case though, as these metrics are for logging and not for modifying the request to OpenAI
