### ISSUE TITLE
Allow users to encrypt their prompts

### ISSUE THREAD

**Issue by chitalian** [Helicone/helicone#35]
We want to allow users to encrypt their prompts. We will do this by passing in an extra header called `helicone-encrypt-prompt` and then encrypt the actual prompt that is stored

**Comment by aavetis** [comment]
curious, why?

and by that logic, would responses be encrypted also?

**Comment by charliemday** [comment]
> curious, why?
> 
> and by that logic, would responses be encrypted also?

I have the need for encrypting certain parts of the prompts. For example I encrypt a user's JSON object in my database but I need to pass it through to GPT however using Helicone it comes up as unencrypted so if someone were to access my Helicone account they would be able to see the data through the prompts. 

Regarding responses that probably also needs to be encrypted (but optionally).

**Comment by chitalian** [comment]
Hi @charliemday thanks for you response. We do have the ability to Omit logs here: https://docs.helicone.ai/features/advanced-usage/omit-logs

I think the solve your problem we can have more intelligent omit features. 

https://github.com/Helicone/helicone/issues/964

I am closing this issue for now, please let me know if you explicitly want the ability to encrypt.

Best,
Justin
