### ISSUE TITLE
Show failed requests in the UI

### ISSUE THREAD

**Issue by alexkreidler** [Helicone/helicone#463]
I'm getting the error `Invalid API base` when using the `Helicone-OpenAI-Api-Base` header via CURL and Python. I'm confused on how this is happening, so it would be great if the Helicone UI included failed requests too, with the full outgoing request and headers to the external API, and its response. Or maybe just adding a more detailed error message for this problem.

**Comment by larrybrazz** [comment]
Hi @alexkreidler I am a frontend developer and this is my first time ever trying to work on an open source project. So, from your comment above this is a UI issue and I will appreciate if you explain to me how I can get started fixing this issue or if you problem have a better issue for me, I will be more than willing to work on it.

**Comment by chitalian** [comment]
Hi @larrybrazz thanks for responding to this. Are you still interested in workin on Helicone? you can join or discord or email me at justin@helicone.ai.


As for this issues specifically, we added a ton more docs here that might solve @alexkreidler 's issue

https://docs.helicone.ai/getting-started/integration-method/azure
