### ISSUE TITLE
Allow proxying to custom LLM APIs

### ISSUE THREAD

**Issue by alexkreidler** [Helicone/helicone#464]
Currently, Helicone only allows people to proxy to the following services:

https://github.com/Helicone/helicone/blob/868d3b7e424c938067611ecbd5c8d37459bdc3ff/worker/src/lib/HeliconeProxyRequest/mapper.ts#L209-L214

However there are many other OpenAI compatible-services, and people are building OpenAI interfaces to open-source models like LLama and company, so Helicone could provide metrics without any code modifications.

**Comment by coreywagehoft** [comment]
I would really like to see this functionality as well so I could use Helicone with something like [LocalAI](https://github.com/go-skynet/LocalAI)

**Comment by chitalian** [comment]
Hi! We are adding this super soon! Next week this should be merged in.

@alexkreidler, and @coreywagehoft - @colegottdank is working on this right now actually :)

**Comment by chingweesze-oursky** [comment]
Hi. May I know if PaLM2 support was added or not? Or its already in some branch pending merge to main?

**Comment by leandrosilvaferreira** [comment]
This was finished ??? I need to track my users tokens consuming.

**Comment by colegottdank** [comment]
@leandrosilvaferreira, hi, you can use our [gateway integration](https://docs.helicone.ai/getting-started/integration-method/gateway)! It allows any target URL. We maintain a [whitelist of providers](https://github.com/Helicone/helicone/blob/c857d5c5cdeb950cf1b13a8fab358c326ad1253f/costs/src/providers/mappings.ts#L14) and if not apart of that whitelist, we allow up to 10k requests per day.

If your desired provider is not there, if valid, we can add it.
