### ISSUE TITLE
Functions should show in response 

### ISSUE THREAD

**Issue by chitalian** [Helicone/helicone#505]
<img width="529" alt="image" src="https://github.com/Helicone/helicone/assets/26822232/27b8cb42-3364-4984-b780-3db9a5e7d6c4">

**Comment by CryogenicPlanet** [comment]
Any timeline on this, happy to make a PR for the same with some guidance or pay to help escalate this?

**Comment by chitalian** [comment]
Hi @CryogenicPlanet We would love to add this, you can join us as an enterprise customer to have things like this escalated. If you are interested please email sales@helicone.ai and we can get you setup on an enterprise plan.
