### ISSUE TITLE
Getting Cloudflare "523: Origin is unreachable" errors

### ISSUE THREAD

**Issue by shreyashankar** [Helicone/helicone#510]
Trying to use the `helicone.openai` module out of the box, but I get the error:

<img width="1728" alt="Screenshot 2023-06-23 at 2 21 58 PM" src="https://github.com/Helicone/helicone/assets/6224969/f63e1494-03da-4a0a-90e3-b1b2086e218f">

With an HTML page with the following paragraph:

"Check your DNS Settings. A 523 error means that Cloudflare could not reach your host web server. The most common cause is that your DNS settings are incorrect. Please contact your hosting provider to confirm your origin IP and then make sure the correct IP is listed for your A record in your Cloudflare DNS Settings page."

**Comment by chitalian** [comment]
Hi @shreyashankar can you provide a bit more information on your environment?

**Comment by chitalian** [comment]
Hi @shreyashankar, I spoke with Cloudflare and this issue should be fixed now :) thanks for reporting
