### ISSUE TITLE
More intelligent rate limits

### ISSUE THREAD

**Issue by chitalian** [Helicone/helicone#570]
We want to have a flag that checks only for 429s

We should also check the response header for the `x-ratelimit-reset-request` and wait for that amount of time before exponential back off. 
 https://platform.openai.com/docs/guides/rate-limits/overview
 
 See this thread for more information
 https://discord.com/channels/1020597994703310878/1021699161831251968/1128947380134359070

**Comment by shishir610** [comment]
Can you assign this to me? @chitalian
