### ISSUE TITLE
Embedding Requests show up on /requests as "Invalid Prompt"

### ISSUE THREAD

**Issue by ScotterC** [Helicone/helicone#596]
What I'd expect
- truncated text of what was being embedded

What did I observe
![Screenshot 2023-07-18 at 9 03 36 AM](https://github.com/Helicone/helicone/assets/313254/0482520f-4165-4700-a332-2318a0dda3c6)
- In the Request column, it prints "Invalid Prompt" for whenever the model is text-embedding-ada-002
- On clicking the request and selecting json, the input text and model appear to be working as normal

What's the problem?
- It's confusing so had me verifying if there was a real issue or whether an end user was trying to jail break the model or something

**Comment by ScottMktn** [comment]
hi @ScotterC , looks like we're missing the embedding model from our  request builder. adding support right now

**Comment by ScottMktn** [comment]
all set!
