### ISSUE TITLE
Please remove hard print statements

### ISSUE THREAD

**Issue by jp803333** [Helicone/helicone#692]
Can we please remove these types of print statements??

```
print("logging", request, provider)
print("logging", async_log, Provider.OPENAI)
```

Used a way around to hide these but it would be better to remove these.

**Comment by pratik2315** [comment]
Hey there! Is this issue still available to work on? If yes, Would love to get involved with it :)

**Comment by chitalian** [comment]
Hi @pratik2315, if you are interested in contributing, please join our discord and tag me @justin or email me at justin@helicone.ai

This issue has been fixed though
