### ISSUE TITLE
Feature Request: Automatic API Key Balancer

### ISSUE THREAD

**Issue by fer112233** [Helicone/helicone#718]
Currently, OpenAI API Chat has certain limits (https://platform.openai.com/docs/guides/rate-limits/overview)
Not just the allowed USD/month, but also requests per minute, and tokens per minute.
In a production environment it could be fairly easy to reach one of these limits, a way of overcoming this is to use multiple OpenAI accounts, with different API keys.

Helicone could, either distribute the load from a list of given API keys or, detect if a request fails and try again with a different API key.

**Comment by chitalian** [comment]
Hi @fer112233 we have this now part of Vaults! I am going to close this ticket now. Note: this is an enterprise feature for now until we iron out the kinks. Closing for now :) 

https://www.helicone.ai/blog/vault
