### ISSUE TITLE
Feature Request: Automatic Model Context Selection

### ISSUE THREAD

**Issue by fer112233** [Helicone/helicone#719]
Currently OpenAI offers 2 main models, 3.5 turbo and 4. Both of these models have a shorter and larger context window version.
3.5 turbo -> 4k & 16k
4 -> 8k & 32K

It would be useful if Helicone could offer the option to automatically select which model to use depending on the request made.

**Comment by chitalian** [comment]
I was thinking the same thing! This is a really cool idea. I am surprised OpenAI doesn't already do this tbh. It sounds so obvious
