### ISSUE TITLE
Token overcounting?

### ISSUE THREAD

**Issue by iamjackg** [Helicone/helicone#733]
I'm a bit puzzled by how Helicone counts tokens for streaming responses.

I wanted to summarize a Python file, so I ran it through [tiktoken](https://github.com/openai/tiktoken) to get a sense of how many tokens it would have used -- got a result of about 4000 tokens. I then sent the request to OpenAI with a very short question at the end of the prompt (something like "Explain this script to a total newcomer to the project"), and got a relatively short answer.

When I checked the request details on the Helicone dashboard, it listed almost 8000 tokens for the prompt, which seems like a pretty extreme difference, even considering all the hidden message tokens and the system prompt. The response was estimated at 304 tokens, and I get 285 when running its plain text through tiktoken, which seems a bit more in line.

Any idea why the difference would be so large?

EDIT: I also just realized that the base gpt-4 has an 8k context, so if the whole prompt had really been 8000+ tokens I should have gotten a cut-off response, right? I think that further points to some overcounting on Helicone's part.

**Comment by chitalian** [comment]
Hi @iamjackg sorry for the incredibly late response here. If you are using ChatGPT there are hidden tokens for each system and assistant message. Helicone accounts for these hidden tokens. 

Hopefully this answers your questions..


The 8k context window is the input window, there is no technical max on the response tokens

**Comment by iamjackg** [comment]
If you read my original submission you'll see that I mentioned the extra tokens for message delimiting, but they can't possibly account for the *doubling* of the total token count I'm seeing.

**Comment by chitalian** [comment]
Thanks @iamjackg for your response - reopening the issue and will take a look
