### ISSUE TITLE
"Failed to create user" on account creation after installation

### ISSUE THREAD

**Issue by geoffroy-aubry** [Helicone/helicone#761]
Hi, I'm trying to run Helicone locally following this: https://github.com/Helicone/helicone/tree/main/docker#readme.

`docker compose up` works without any errors

The come the account creation step via http://localhost:8989/project/default/auth/users. Unfortunately the creation of a new user systematically aborts with this error message: `Failed to create user: An error has occured: Fail to fetch`.
No special log in `docker compose logs -f`. Only these:
```
supabase-imgproxy               | INFO    [2023-08-28T09:51:45Z] Started /health  request_id=mPSaduFrD2YsjxDDLDduK method=GET client_ip=127.0.0.1
supabase-imgproxy               | INFO    [2023-08-28T09:51:45Z] Completed in 359.124µs /health  request_id=mPSaduFrD2YsjxDDLDduK method=GET status=200 client_ip=127.0.0.1
```

How can we please investigate further?
Thank you in advance.

**Comment by n8vision** [comment]
are you on localhost? if not you need to edit .env to reflect the public IP/ domain in a few places, and fix docker-compose.yml here:

  web:
    container_name: helicone-web
    image: helicone/web:latest
    restart: unless-stopped
    ports:
      # Pass down internal port because it's set dynamically by other services
      - 3000:3000
    environment:
      NEXT_PUBLIC_SUPABASE_URL: http://localhost:${KONG_HTTP_PORT}
      
 
as localhost should not be baked into NEXT_PUBLIC_SUPABASE_URL, I think.

**Comment by geoffroy-aubry** [comment]
Hi, I'm on localhost, and ANON_KEY and SERVICE_ROLE_KEY in `.env` match those in `volumes/api/kong.yml`.
Aren't there any error logs to analyse?
