### ISSUE TITLE
Azure OpenAI costs not being calculated

### ISSUE THREAD

**Issue by aavetis** [Helicone/helicone#777]
Looks like a bug where request costs are not calculated if you're using Azure OpenAI. This is potentially because the return object from AZ OAI endpoint is slightly different from the regular OpenAI endpoint. I can provide detailed logs if necessary.

discussion in discord [here](https://discord.com/channels/1020597994703310878/1074508878030577684/1146829253158117526) and [here](https://discord.com/channels/1020597994703310878/1074508878030577684/1146585614238617671)

![image](https://github.com/Helicone/helicone/assets/3076502/80b98da4-e7a8-49e6-a899-9c66596d7337)

**Comment by yigitkonur** [comment]
I can see that the system is currently calculating costs; should I be concerned about its accuracy?

**Comment by aavetis** [comment]
nope, looks like it's fixed! not sure when it was deployed, but closing this since i can see it too.
