### ISSUE TITLE
Feedback extensions - custom feedback

### ISSUE THREAD

**Issue by chitalian** [Helicone/helicone#811]
We should maybe have dedicated columns for common feedback operations that we can optimize for.
- Positive/Negative
- Score
This way the aggregations can be fast and well optimized.

I think we should also support a column that is just generic with custom types that we can predefine a set of aggregation operations and visualizations for.

```
type CustomFeedbackValue = {
{
   _type: "int",
   value: number
} | {
  _type: "string",
  value: string
} | {
  _type: "bool",
  value: boolean
};
type CustomFeedbackColumn = {
 key: string
 value: CustomFeedbackValue
 }
```

**Comment by colegottdank** [comment]
Completed, we added the ability to add properties after the request/response was made which is essentially custom feedback:

https://docs.helicone.ai/features/advanced-usage/custom-properties
