### ISSUE TITLE
Error using similarity_search from local faiss

### ISSUE THREAD

**Issue by karpediemnow** [Helicone/helicone#862]
If I try to use helicone in a similarity verctor search i get a 

openai.error.InvalidRequestError: Invalid URL (POST /v1/openai/deployments/my-model-embedding-ada-002/embeddings)

**Comment by chitalian** [comment]
Hi @karpediemnow 

Sorry you are experiencing this issue. I am going to take a look at this ASAP. 

In the meantime, would you be able to send me some short instructions to recreate the issue? 

Can you provide an example request or code snippet?

**Comment by karpediemnow** [comment]
Hi @chitalian 
Thanks for your quickly response this is the code snippet to reproduce:

`       embeddings = OpenAIEmbeddings(
                        deployment="MY-text-embedding-ada-002"
                        model = "text-embedding-ada-002",
                        chunk_size = 1
                    )
      #Load my local knoledge base
      knowledge_base = FAISS.load_local("KnowledgeBase/MyKB.FAISS", embeddings)

      #Similarity Search..
      docs = knowledge_base.similarity_search(user_question)

    #KABOOOMMMM!!!
`
Thanks for your time ;)

GP

**Comment by chitalian** [comment]
Hi @karpediemnow - Is this using LangChain?

**Comment by karpediemnow** [comment]
@chitalian yeep
