### ISSUE TITLE
Remove `axios` from `helicone-node`

### ISSUE THREAD

**Issue by ConProgramming** [Helicone/helicone#872]
To match [openai v4](https://github.com/openai/openai-node/discussions/182), we should remove `axios`.

This lets the package be smaller and faster to run better on all platforms, especially those like Cloudflare Workers.

**Comment by chitalian** [comment]
Hi @ConProgramming we added this to our next sprint. Thanks for reporting

**Comment by colegottdank** [comment]
This has been completed in the newest version of helicone node. https://www.npmjs.com/package/@helicone/helicone#as-of-october-25th-this-package-is-deprecated
