### ISSUE TITLE
Front-end Error when create API keys.

### ISSUE THREAD

**Issue by xuyuan23** [Helicone/helicone#877]
I execute the command below, 'xxx.xxx.xxx.xxx' is my cloud service's ip. 
```
sudo docker compose up -d --env NEXT_PUBLIC_BASE_PATH=http://xxx.xxx.xxx.xxx:8788  --env SITE_URL=http://xxx.xxx.xxx.xxx:8989 --env SUPABASE_PUBLIC_URL=http://xxx.xxx.xxx.xxx:8000 --env API_EXTERNAL_URL=http://xxx.xxx.xxx.xxx:8000
```
Then I create a user rightly in website 'http://xxx.xxx.xxx.xxx:8989/project/default/auth/users', and login by the user rightly, Next I create API Key but no response ? no request was sent, and the console shows:
`keys-85a689df7727e7e3.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'digest').`

I don't know why ?

**Comment by xuyuan23** [comment]
![image](https://github.com/Helicone/helicone/assets/26043513/22699284-9e24-4f78-a714-88888b5d87b8)

**Comment by chitalian** [comment]
Hi @xuyuan23 are you still seeing this error?
