### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by gkossakowski** [Helicone/helicone#883]
Path: /getting-started/integration-method/anthropic

the url param is `base_url` now: https://github.com/anthropics/anthropic-sdk-python/blob/main/src/anthropic/_client.py#L64

**Comment by fauh45** [comment]
If you don't mind I might add another issue for the docs as well.

Anthropic Node.js client already prepends the `/v1/completion`, so if the documentation is as to be followed (see below)
![Anthropic documentation regarding Anthropic request](https://github.com/Helicone/helicone/assets/7534613/39878259-9d5a-4267-9569-ac740f73fc95)

It would result in Anthropic Node.js client to hit `/v1/v1/completion` which result in 404.
