### ISSUE TITLE
Anthropic stats missing

### ISSUE THREAD

**Issue by fauh45** [Helicone/helicone#937]
When proxy-ing stats to Helicone using Anthropic model there's some stats missing from the page. Here's the one I've found

- Total tokens
- Latency
- LLM Response

Total tokens and latency seems to be missing from the API request to the server. So maybe `worker` issue? Here's a snapshot of `/api/request` result.

```json
{
    "data": [
        {
            "response_id": "<There was an id but now it's redacted>",
            "response_created_at": "2023-10-14T04:30:24.031Z",
            "response_body": {
                "body": {
                    "stop": "|END|",
                    "model": "claude-instant-1.2",
                    "log_id": "<There was and id but now it's redacted>",
                    "completion": " <There was some text but now it's redacted>\" ",
                    "stop_reason": "stop_sequence"
                },
                "helicone_error": "error parsing response",
                "parse_response_error": "error parsing response, TypeError: Fetch API cannot load: undefined, {\"completion\":\" <There was some text but now it's redacted>" \",\"stop_reason\":\"stop_sequence\",\"model\":\"claude-instant-1.2\",\"stop\":\"|END|\",\"log_id\":\"<There was an id but now it's redacted>\"}"
            },
            "response_status": 200,
            "request_id": "6ebc5890-93b6-4234-8d69-292449b83c92",
            "request_created_at": "2023-10-14T04:30:19.674Z",
            "request_body": {
                "model": "claude-instant-1.2",
                "prompt": "<There was some text but now it's redacted>",
                "metadata": {
                    "user_id": "52dd058ca49105049bc7ca02b66b39814cc7ada4"
                },
                "temperature": 0.5,
                "stop_sequences": [
                    "|END|"
                ],
                "max_tokens_to_sample": 512
            },
            "request_path": "https://anthropic.hconeai.com/v1/complete",
            "request_user_id": "<There was an id but now it's redacted>",
            "request_properties": {
                <There was an object but now it's redacted>
            },
            "request_formatted_prompt_id": null,
            "request_prompt_values": null,
            "provider": "ANTHROPIC",
            "request_feedback": null,
            "helicone_user": "<There was an id but now it's redacted>",
            "delay_ms": -1,
            "total_tokens": null,
            "completion_tokens": null,
            "prompt_tokens": null,
            "prompt_name": null,
            "prompt_regex": null,
            "node_id": null,
            "feedback_created_at": null,
            "feedback_id": null,
            "feedback_rating": null,
            "request_prompt": "<There was some text but now it's redacted>",
            "response_prompt": null
        }
    ],
    "error": null
}
```

But for LLM response being missing I think it's related to #929. Now it doesn't result in an error, but I think what was passed to `body` shouldn't be an object, but a string, maybe?

**Comment by fauh45** [comment]
So I've been testing it in my local machine and the result is somehow flipped. First I tried to start a Anthropic Proxy worker by setting `WORKER_TYPE = "ANTHROPIC_PROXY"`, and there's no problem at all getting all the stats in the sidebar (shown below).

![image](https://github.com/Helicone/helicone/assets/7534613/4c854697-d387-45a0-b466-61dc2edec2b6)

And yet after flipping it back to `WORKER_TYPE = "OPENAI_PROXY"` it results in the same missing stats as reported here.

![image](https://github.com/Helicone/helicone/assets/7534613/f97683bb-5dea-4473-b5e5-2d571ed4f190)

After a bit of digging around I found `parseResponse` to behave weirdly. In line 266 - 268, where (I assume) it's a conditional for request that's sent to OpenAI and is successful (thus `status = 200`), it instead check if the `status !== 200`. Shouldn't that be the other way around?

Here's a pic from the inspect window, as you can see the current request is successful. And yet it responds with parsing error otherwise.

![image](https://github.com/Helicone/helicone/assets/7534613/5803cc93-c694-407e-adb5-3e7a7ba225ae)

**Comment by chitalian** [comment]
This is resolved right? @fauh45

**Comment by fauh45** [comment]
Haven't really checked, but with the recent PR it should be. Thank you @chitalian!
