### ISSUE TITLE
Difficulty with docs: Langchain?

### ISSUE THREAD

**Issue by ErwinAI** [Helicone/helicone#942]
While using Langchain is great (and many use it), it unfortunately isn't compatible with the feedback mechanism, because it's impossible to retrieve response headers. Because of that, 'helicone-id' header can't be retrieved. Is there any other way to still integrate the feedback functionality while using Langchain?

Path: /features/advanced-usage/feedback

**Comment by chitalian** [comment]
Hi @ErwinAI Thanks for your message. I added docs on how to do this 

https://github.com/Helicone/helicone/pull/956

You can see the docs here:
https://docs.helicone.ai/features/advanced-usage/feedback

But the idea is that you can create the request_id before hand

```python

import uuid
from langchain.chat_models.openai import ChatOpenAI
import requests
import json
HELICONE_AUTH = "Bearer <API_KEY>"

def provide_feedback(heliconeId, rating):
    url = "https://api.hconeai.com/v1/feedback"
    headers = {
        "Helicone-Auth": HELICONE_AUTH,
        "Content-Type": "application/json",
    }
    data = {
        "helicone-id": heliconeId,
        "rating": rating  # True for positive, False for negative
    }

    response = requests.post(url, headers=headers, data=json.dumps(data))


request_id = str(uuid.uuid4())
ChatOpenAI.openai_api_base = "https://oai.hconeai.com/v1"
llm = ChatOpenAI(
    openai_api_base="https://oai.hconeai.com/v1",
    headers={
        "Helicone-Auth": HELICONE_AUTH,
        "Helicone-Request-Id": request_id
    }
)

llm_result = llm.predict("What is a Helicone")
provide_feedback(request_id, True)

```

**Comment by ErwinAI** [comment]
@chitalian Ah gotcha, I did not know I can use the 'Helicone-Request-Id' to set an ID I build myself beforehand.
This works, thank you 🙇!

**Comment by chitalian** [comment]
@ErwinAI no worries! Thanks for bringing it to our attention and helping us improve our docs
