### ISSUE TITLE
Erroneous documentation

### ISSUE THREAD

**Issue by rafalzawadzki** [Helicone/helicone#946]
The documentation at https://docs.helicone.ai/features/advanced-usage/custom-rate-limits has incorrect code snippets for NodeJS and Python. Specifically, the part about setting rate limits based on a custom "IP" property:

```
"Helicone-Property-IP": "111.1.1.1",
"Helicone-RateLimit-Policy": "1000;w=60;s=ip_address",
```

The incorrect part: segment name `s=ip_address` is different from the custom property name `IP`.

If used directly, this code  will result in very hard to debug errors with no explanation. Something to those lines:

```
 Error: Unknown error occurred
    at (node_modules/.pnpm/openai@4.0.0/node_modules/openai/error.mjs:52:13)
    at (node_modules/.pnpm/openai@4.0.0/node_modules/openai/core.mjs:256:20)
    at (node_modules/.pnpm/openai@4.0.0/node_modules/openai/core.mjs:296:23)
    at (app/api/chat/route.ts:73:26)
    at 
{
  status: 500,
  headers: {
  cf-ray: '8171000b25de2c55-FRA',
  connection: 'keep-alive',
  content-length: '228',
  content-type: 'application/json;charset=UTF-8',
  date: 'Mon, 16 Oct 2023 14:30:30 GMT',
  helicone-error: 'true',
  server: 'cloudflare'
},
  error: undefined,
  code: undefined,
  param: undefined,
  type: undefined
}
```

Solution: always make sure the segment name has an equivalent in a custom property.

**Comment by chitalian** [comment]
Great catch @rafalzawadzki !

Just merged in a fix
https://github.com/Helicone/helicone/pull/955
